"""

Revision ID: 15b226ca2307
Revises: e91dd8fc2f90
Create Date: 2024-08-12 18:17:48.456505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b226ca2307'
down_revision: Union[str, None] = 'e91dd8fc2f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('concluida', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefas', 'concluida')
    # ### end Alembic commands ###
